schema: '**/*.graphqls'
schemaEntrypoint: 'lib/type-defs.graphqls'
documents: '**/*.graphql'
plugins:
  - typescript
  - typescript-operations
  - typescript-react-apollo
  # - typed-document-node
config:
  apolloReactCommonImportFrom: "@apollo/client"
  apolloReactHooksImportFrom: "@apollo/client"
cacheDir: __generated__