/* 214c9863de73b3425fa9dbe2f940843908f1c398
 * This file is automatically generated by graphql-let. */

export declare type Maybe<T> = T | null;
export declare type Exact<T extends {
    [key: string]: unknown;
}> = {
    [K in keyof T]: T[K];
};
/** All built-in and custom scalars, mapped to their actual values */
export declare type Scalars = {
    ID: string;
    String: string;
    Boolean: boolean;
    Int: number;
    Float: number;
};
export declare type Query = {
    __typename?: 'Query';
    viewer: User;
    viewerRemote: Array<Maybe<UserRemote>>;
};
export declare type User = {
    __typename?: 'User';
    id: Scalars['ID'];
    name: Scalars['String'];
    status: Scalars['String'];
};
export declare type UserRemote = {
    __typename?: 'UserRemote';
    id: Scalars['ID'];
    name: Scalars['String'];
    status: Scalars['String'];
};
export declare type PartialFragment = ({
    __typename?: 'User';
} & Pick<User, 'id' | 'name'>);
export declare type PartialRemoteFragment = ({
    __typename?: 'UserRemote';
} & Pick<UserRemote, 'id' | 'name'>);
export declare const PartialFragmentDoc: import("@apollo/client").DocumentNode;
export declare const PartialRemoteFragmentDoc: import("@apollo/client").DocumentNode;
